user.email: devdoomari@gmail.com
user.name: devdoomari-circlei
jobs:
  push_dist:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: install-yarn-globally
          command: 'sudo npm install -g yarn'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: build
          command: yarn build
      - run:
          name: pull-merge-build-forcepush
          command: |
            git checkout -b $'dist-'"$CIRCLE_BRANCH"
            ./.circleci/pullAndMerge.sh
            git push --set-upstream origin $'dist-'"$CIRCLE_BRANCH" --force --follow-tags
  push_master:
    docker:
      - image: circleci/node:8-browsers
    environment:
      GIT_COMMITER_NAME: 'devdoomari-circleci'
      GIT_COMMITER_EMAIL: 'devdoomari@gmail.com'
      GIT_AUTHOR_NAME: 'devdoomari-circleci'
      GIT_AUTHOR_EMAIL: 'devdoomari@gmail.com'
    steps:
      - checkout
      - run:
          name: Set git username/email
          command: 'mkdir -p ~/.git && git config --global user.email "devdoomari@gmail.com" && git config --global user.name "devdoomari.circleci"'
      - run:
          name: install-yarn-globally
          command: 'sudo npm install -g yarn'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: build
          command: yarn build
      - run:
          name: pull-merge-build-forcepush
          command: |
            git checkout master
            ./.circleci/pullAndMerge.sh
            git push --set-upstream origin master --force --follow-tags

workflows:
  version: 2
  build_and_push:
    jobs:
      - push_dist:
          filters:
            branches:
              ignore:
               - /^dist*/
               - develop
               - master
      - push_master:
          filters:
            branches:
              only: develop
